"use client";

import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Calendar as CalendarIcon, Loader2, Package, User, Settings, FileText, Plus, Trash2, ArrowRight, ArrowLeft, CheckCircle2, UploadCloud, X, Image as ImageIcon } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "sonner";
import { cn, capitalizeName } from "@/lib/utils";
import { SearchableSelect } from "@/components/ui/searchable-select";
import { ConfirmationDialog } from "@/components/ui/confirmation-dialog";

import { WorkOrder } from "@/lib/types";

interface CreateWorkOrderModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSuccess?: () => void;
    orderToEdit?: WorkOrder | null;
}

interface Option {
    id: number;
    nombre: string;
}

interface Maquina {
    id: number;
    nombre: string;
}

interface ProcessItem {
    id: string; // Temporary ID for UI
    proceso_id: string;
    // operario_id: string; // Removed per user request
    // maquinaria_id: string; // Removed per user request
    fecha_inicio: string;
    fecha_fin: string;
}

interface Articulo {
    id: number;
    cod_articulo: string;
    descripcion: string;
}

export default function CreateWorkOrderModal({ isOpen, onClose, onSuccess }: CreateWorkOrderModalProps) {
    const [loading, setLoading] = useState(false);
    const [submitting, setSubmitting] = useState(false);
    const [activeTab, setActiveTab] = useState("general");
    const [showConfirmSubmit, setShowConfirmSubmit] = useState(false);
    const [showConfirmCancel, setShowConfirmCancel] = useState(false);


    // Form state
    const [generalData, setGeneralData] = useState({
        // numero_orden removed - generated by backend
        cliente: "", // Legacy or display name
        cliente_id: "", // New ID field
        descripcion: "",
        prioridad_id: "",
        articulo_id: "",
        fecha_prometida: "",
    });

    const [detailsData, setDetailsData] = useState({
        cantidad: "",
        observaciones: "",
    });

    const [processes, setProcesses] = useState<ProcessItem[]>([]);
    const [files, setFiles] = useState<File[]>([]);

    // Data options
    const [prioridades, setPrioridades] = useState<Option[]>([]);
    const [procesosOptions, setProcesosOptions] = useState<Option[]>([]);
    const [articulos, setArticulos] = useState<Articulo[]>([]);
    const [clientes, setClientes] = useState<Option[]>([]); // New state
    const [operarios, setOperarios] = useState<{ id: number, nombre: string, apellido: string }[]>([]);
    const [maquinarias, setMaquinarias] = useState<Maquina[]>([]);

    useEffect(() => {
        if (isOpen) {
            fetchData();
        }
    }, [isOpen]);

    const fetchData = async () => {
        setLoading(true);
        try {
            const [prioridadesRes, procesosRes, operariosRes, maquinariasRes, articulosRes, clientesRes] = await Promise.all([
                fetch("http://localhost:8000/prioridades"),
                fetch("http://localhost:8000/procesos"),
                fetch("http://localhost:8000/operarios"),
                fetch("http://localhost:8000/maquinarias"),
                fetch("http://localhost:8000/articulos"),
                fetch("http://localhost:8000/clientes") // Fetch clients
            ]);

            if (prioridadesRes.ok) {
                const data = await prioridadesRes.json();
                const rawData = Array.isArray(data) ? data : (data.data || []);
                setPrioridades(rawData.map((p: any) => ({ id: p.id, nombre: p.descripcion })));
            }
            if (clientesRes.ok) {
                const data = await clientesRes.json();
                const rawData = Array.isArray(data) ? data : (data.data || []);
                setClientes(rawData.map((c: any) => ({ id: c.id, nombre: c.nombre })));
            }
            if (procesosRes.ok) {
                const data = await procesosRes.json();
                setProcesosOptions(Array.isArray(data) ? data : (data.data || []));
            }
            if (operariosRes.ok) {
                const data = await operariosRes.json();
                setOperarios(Array.isArray(data) ? data : (data.data || []));
            }
            if (maquinariasRes.ok) {
                const data = await maquinariasRes.json();
                setMaquinarias(Array.isArray(data) ? data : (data.data || []));
            }
            if (articulosRes.ok) {
                const data = await articulosRes.json();
                setArticulos(Array.isArray(data) ? data : (data.data || []));
            }
        } catch (error) {
            console.error("Error fetching data:", error);
        } finally {
            setLoading(false);
        }
    };

    const handleAddProcess = () => {
        const newProcess: ProcessItem = {
            id: Math.random().toString(36).substr(2, 9),
            proceso_id: "",
            fecha_inicio: "",
            fecha_fin: "",
        };
        setProcesses([...processes, newProcess]);
    };

    const handleRemoveProcess = (id: string) => {
        setProcesses(processes.filter(p => p.id !== id));
    };

    const handleProcessChange = (id: string, field: keyof ProcessItem, value: string) => {
        setProcesses(processes.map(p => p.id === id ? { ...p, [field]: value } : p));
    };

    const validateForm = () => {
        if (!generalData.cliente_id || !generalData.descripcion || !generalData.prioridad_id || !generalData.articulo_id) {
            toast.error("Por favor completa los campos obligatorios en la pestaña General");
            // If we are not in General tab, maybe switch to it? 
            // The user wants free navigation, so we just alert.
            // Optionally we can switch activeTab to "general" to show the user where the error is.
            setActiveTab("general");
            return false;
        }

        if (processes.length === 0) {
            toast.error("Debes agregar al menos un proceso");
            setActiveTab("procesos");
            return false;
        }

        for (const p of processes) {
            if (!p.proceso_id || !p.fecha_inicio || !p.fecha_fin) {
                toast.error("Por favor completa la información de todos los procesos");
                setActiveTab("procesos");
                return false;
            }
        }
        return true;
    };

    const handleNextStep = () => {
        if (activeTab === "general") setActiveTab("procesos");
        else if (activeTab === "procesos") setActiveTab("detalles");
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // Trigger confirmation if validation passes
        if (validateForm()) {
            setShowConfirmSubmit(true);
        }
    };

    const performSubmission = async () => {
        setSubmitting(true);

        // Find selected article for auto-filling observations
        const selectedArticle = articulos.find(a => a.id.toString() === generalData.articulo_id);
        const articleDescription = selectedArticle ? `${selectedArticle.cod_articulo} - ${selectedArticle.descripcion}` : "";

        const fullData = {
            id_otvieja: 0, // 0 triggers backend auto-generation
            observaciones: articleDescription, // Solo nombre del articulo
            detalle: detailsData.observaciones ? `${generalData.descripcion}\n\nNota: ${detailsData.observaciones}`.trim() : generalData.descripcion, // Descripcion + Notas
            id_cliente: parseInt(generalData.cliente_id), // Send ID
            cliente: clientes.find(c => c.id.toString() === generalData.cliente_id)?.nombre || "", // Send name for display (optional)
            unidades: detailsData.cantidad ? parseInt(detailsData.cantidad) : 0,

            id_prioridad: parseInt(generalData.prioridad_id),
            id_sector: 1, // Hardcoded as per user request
            id_articulo: parseInt(generalData.articulo_id),

            fecha_orden: new Date().toISOString(),
            fecha_entrada: new Date().toISOString(),
            fecha_prometida: generalData.fecha_prometida || new Date().toISOString(),
            fecha_entrega: null,

            procesos: processes.map(p => ({
                proceso_id: parseInt(p.proceso_id),
                operario_id: null,
                maquinaria_id: null,
                fecha_inicio: new Date(p.fecha_inicio).toISOString(),
                fecha_fin: new Date(p.fecha_fin).toISOString()
            }))
        };

        try {
            const formData = new FormData();
            formData.append('data', JSON.stringify(fullData));

            files.forEach(file => {
                formData.append('files', file);
            });

            const response = await fetch("http://localhost:8000/ordenes", {
                method: "POST",
                body: formData,
            });

            if (!response.ok) {
                const errorData = await response.json();
                console.error("Error response from backend:", errorData);

                let errorMessage = "Error al crear la orden";

                // Parse standardized backend errors (ResponseDTO)
                if (errorData.errors && Array.isArray(errorData.errors) && errorData.errors.length > 0) {
                    errorMessage = errorData.errors.map((e: any) => e.message).join(", ");
                }
                // Parse standard FastAPI details
                else if (typeof errorData.detail === 'string') {
                    errorMessage = errorData.detail;
                } else if (errorData.detail && Array.isArray(errorData.detail)) {
                    // Pydantic validation errors
                    errorMessage = errorData.detail.map((e: any) => e.msg).join(", ");
                } else if (errorData.message) {
                    errorMessage = errorData.message;
                }

                throw new Error(errorMessage);
            }

            toast.success("Orden de Trabajo creada correctamente");
            onSuccess?.();
            onClose();
            resetForm();
        } catch (error) {
            console.error("Error creating order:", error);
            toast.error(error instanceof Error ? error.message : "Error desconocido al crear la orden");
        } finally {
            setSubmitting(false);
        }
    };

    const resetForm = () => {
        setGeneralData({
            cliente: "",
            cliente_id: "",
            descripcion: "",
            prioridad_id: "",
            articulo_id: "",
            fecha_prometida: "",
        });
        setDetailsData({
            cantidad: "",
            observaciones: "",
        });
        setProcesses([]);
        setFiles([]);
        setActiveTab("general");
    };

    const handleAttemptClose = () => {
        // Check if form is dirty (has data)
        const isDirty = generalData.cliente_id || generalData.descripcion || processes.length > 0;

        if (isDirty) {
            setShowConfirmCancel(true);
        } else {
            handleClose();
        }
    };

    const handleClose = () => {
        resetForm();
        onClose();
        setActiveTab("general");
    };

    return (
        <>
            <ConfirmationDialog
                isOpen={showConfirmSubmit}
                onClose={() => setShowConfirmSubmit(false)}
                onConfirm={performSubmission}
                title="Crear Orden de Trabajo"
                description="¿Estás seguro de que quieres crear esta Orden de Trabajo? Verificá que todos los datos sean correctos."
                confirmText="Sí, crear orden"
            />

            <ConfirmationDialog
                isOpen={showConfirmCancel}
                onClose={() => setShowConfirmCancel(false)}
                onConfirm={handleClose}
                title="Cancelar Creación"
                description="Si cancelas ahora, perderás todos los datos ingresados. ¿Estás seguro?"
                confirmText="Sí, cancelar"
                cancelText="Volver"
                variant="destructive"
            />

            <Dialog open={isOpen} onOpenChange={(open) => !open && handleAttemptClose()}>

                <DialogContent className="sm:max-w-[95vw] md:max-w-[1200px] bg-white rounded-xl shadow-2xl border-0 h-[85vh] flex flex-col p-0 gap-0 overflow-hidden">
                    <DialogHeader className="p-6 pb-4 border-b bg-white flex-shrink-0">
                        <DialogTitle className="text-2xl font-bold text-gray-900 flex items-center gap-3">
                            <div className="p-2.5 bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl shadow-lg shadow-blue-500/20">
                                <CalendarIcon className="h-6 w-6 text-white" />
                            </div>
                            <div className="flex flex-col">
                                <span>Nueva Orden de Trabajo</span>
                                <span className="text-sm font-normal text-gray-500 mt-0.5">Completa la información para crear una nueva OT</span>
                            </div>
                        </DialogTitle>
                    </DialogHeader>

                    <form onSubmit={handleSubmit} className="flex flex-col flex-1 min-h-0">
                        <div className="flex-1 overflow-y-auto p-6 relative">
                            <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
                                <TabsList className="grid w-full grid-cols-2 mb-8 bg-gray-100/50 p-1 rounded-xl sticky top-0 z-10 backdrop-blur-sm">
                                    <TabsTrigger value="general" className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm data-[state=active]:text-blue-600 transition-all">
                                        <FileText size={16} className="mr-2" />
                                        1. Información General y Detalles
                                    </TabsTrigger>
                                    <TabsTrigger value="procesos" className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm data-[state=active]:text-blue-600 transition-all">
                                        <Settings size={16} className="mr-2" />
                                        2. Procesos y Recursos (Opcional)
                                    </TabsTrigger>
                                </TabsList>

                                {/* Tab: General */}
                                <TabsContent value="general" className="space-y-6 mt-0 animate-in fade-in-50 slide-in-from-left-2 duration-300">
                                    <div className="grid grid-cols-2 gap-6">
                                        <div className="space-y-2">
                                            <Label htmlFor="articulo" className="text-sm font-semibold text-gray-700">
                                                Artículo / Producto <span className="text-red-500">*</span>
                                            </Label>
                                            <SearchableSelect
                                                options={articulos.map(a => ({ value: a.id.toString(), label: `${a.cod_articulo} - ${a.descripcion}` }))}
                                                value={generalData.articulo_id}
                                                onValueChange={(val) => setGeneralData({ ...generalData, articulo_id: val })}
                                                placeholder="Seleccionar artículo"
                                            />
                                        </div>

                                        <div className="space-y-2">
                                            <Label htmlFor="cliente" className="text-sm font-semibold text-gray-700">
                                                Cliente <span className="text-red-500">*</span>
                                            </Label>
                                            <SearchableSelect
                                                options={clientes.map(c => ({ value: c.id.toString(), label: c.nombre }))}
                                                value={generalData.cliente_id}
                                                onValueChange={(val) => setGeneralData({ ...generalData, cliente_id: val })}
                                                placeholder="Seleccionar cliente"
                                            />
                                        </div>
                                    </div>

                                    <div className="space-y-2">
                                        <Label htmlFor="descripcion" className="text-sm font-semibold text-gray-700">
                                            Descripción del Trabajo <span className="text-red-500">*</span>
                                        </Label>
                                        <Textarea
                                            id="descripcion"
                                            placeholder="Describe el trabajo a realizar..."
                                            value={generalData.descripcion}
                                            onChange={(e) => setGeneralData({ ...generalData, descripcion: e.target.value })}
                                            className="min-h-[100px] border-gray-200 focus:border-blue-500 focus:ring-blue-500/20 bg-gray-50/30 resize-none"
                                            required
                                        />
                                    </div>

                                    <div className="grid grid-cols-3 gap-6">
                                        <div className="space-y-2">
                                            <Label htmlFor="prioridad" className="text-sm font-semibold text-gray-700">
                                                Prioridad <span className="text-red-500">*</span>
                                            </Label>
                                            <SearchableSelect
                                                options={prioridades.map(p => ({ value: p.id.toString(), label: p.nombre }))}
                                                value={generalData.prioridad_id}
                                                onValueChange={(val) => setGeneralData({ ...generalData, prioridad_id: val })}
                                                placeholder="Seleccionar prioridad"
                                            />
                                        </div>

                                        <div className="space-y-2">
                                            <Label htmlFor="fecha_prometida" className="text-sm font-semibold text-gray-700">
                                                Fecha Prometida
                                            </Label>
                                            <Input
                                                id="fecha_prometida"
                                                type="date"
                                                value={generalData.fecha_prometida ? generalData.fecha_prometida.split('T')[0] : ''}
                                                onChange={(e) => setGeneralData({ ...generalData, fecha_prometida: e.target.value })}
                                                className="h-11 border-gray-200 focus:border-blue-500 focus:ring-blue-500/20 bg-gray-50/30"
                                            />
                                        </div>

                                        <div className="space-y-2">
                                            <Label htmlFor="cantidad" className="text-sm font-semibold text-gray-700">
                                                Cantidad
                                            </Label>
                                            <Input
                                                id="cantidad"
                                                type="number"
                                                placeholder="Ej: 100"
                                                value={detailsData.cantidad}
                                                onChange={(e) => setDetailsData({ ...detailsData, cantidad: e.target.value })}
                                                className="h-11 border-gray-200 focus:border-blue-500 focus:ring-blue-500/20 bg-gray-50/30"
                                                min="1"
                                            />
                                        </div>
                                    </div>

                                    <div className="space-y-2 pt-4">
                                        <Label className="text-sm font-semibold text-gray-700">
                                            Archivos Adjuntos (Planos, Especificaciones)
                                        </Label>
                                        <div className="border-2 border-dashed border-gray-200 rounded-xl p-6 transition-all hover:border-blue-400 hover:bg-blue-50/30 group text-center cursor-pointer relative">
                                            <input
                                                type="file"
                                                multiple
                                                accept="image/*,.pdf"
                                                className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"
                                                onChange={(e) => {
                                                    if (e.target.files) {
                                                        const newFiles = Array.from(e.target.files);
                                                        setFiles(prev => [...prev, ...newFiles]);
                                                    }
                                                }}
                                            />
                                            <div className="flex flex-col items-center gap-2 pointer-events-none">
                                                <div className="p-3 bg-blue-50 text-blue-600 rounded-full group-hover:scale-110 transition-transform">
                                                    <UploadCloud className="w-6 h-6" />
                                                </div>
                                                <div className="text-sm text-gray-600">
                                                    <span className="font-semibold text-blue-600">Haz clic para subir</span> o arrastra y suelta
                                                </div>
                                                <p className="text-xs text-gray-400">PDF, PNG, JPG (máx. 10MB)</p>
                                            </div>
                                        </div>

                                        {files.length > 0 && (
                                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-4">
                                                {files.map((file, index) => (
                                                    <div key={index} className="flex items-center justify-between p-3 bg-gray-50 border border-gray-100 rounded-lg group hover:border-blue-200 transition-all">
                                                        <div className="flex items-center gap-3 overflow-hidden">
                                                            <div className="p-2 bg-white rounded-md border border-gray-100 text-gray-500">
                                                                {file.type.includes('pdf') ? (
                                                                    <FileText className="w-4 h-4 text-red-500" />
                                                                ) : (
                                                                    <ImageIcon className="w-4 h-4 text-blue-500" />
                                                                )}
                                                            </div>
                                                            <div className="flex flex-col min-w-0">
                                                                <span className="text-sm font-medium text-gray-700 truncate">{file.name}</span>
                                                                <span className="text-xs text-gray-400">{(file.size / 1024 / 1024).toFixed(2)} MB</span>
                                                            </div>
                                                        </div>
                                                        <Button
                                                            type="button"
                                                            variant="ghost"
                                                            size="icon"
                                                            onClick={() => setFiles(files.filter((_, i) => i !== index))}
                                                            className="h-8 w-8 text-gray-400 hover:text-red-500 hover:bg-red-50"
                                                        >
                                                            <X className="w-4 h-4" />
                                                        </Button>
                                                    </div>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                </TabsContent>

                                {/* Tab: Procesos */}
                                <TabsContent value="procesos" className="space-y-6 mt-0 animate-in fade-in-50 slide-in-from-right-2 duration-300">
                                    <div className="flex items-center justify-between mb-2">
                                        <div className="space-y-1">
                                            <h3 className="text-lg font-semibold text-gray-900">Procesos de la Orden</h3>
                                            <p className="text-sm text-gray-500">Define la secuencia de procesos para esta orden (Opcional)</p>
                                        </div>
                                        <Button
                                            type="button"
                                            onClick={handleAddProcess}
                                            className="bg-blue-50 text-blue-600 hover:bg-blue-100 border border-blue-200 shadow-sm"
                                        >
                                            <Plus className="w-4 h-4 mr-2" />
                                            Agregar Proceso
                                        </Button>
                                    </div>

                                    <div className="space-y-4">
                                        {processes.length === 0 ? (
                                            <div className="text-center py-12 border-2 border-dashed border-gray-200 rounded-xl bg-gray-50/50">
                                                <div className="w-12 h-12 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-3">
                                                    <Settings className="w-6 h-6 text-gray-400" />
                                                </div>
                                                <p className="text-gray-500 font-medium">No hay procesos agregados</p>
                                                <p className="text-sm text-gray-400 mt-1">Si no agregas procesos, se podrá crear la orden igual.</p>
                                            </div>
                                        ) : (
                                            processes.map((process, index) => (
                                                <Card key={process.id} className="border border-gray-200 shadow-sm hover:shadow-md transition-all duration-200 group">
                                                    <CardContent className="p-5">
                                                        <div className="flex items-center justify-between mb-4">
                                                            <div className="flex items-center gap-3">
                                                                <div className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-bold text-sm">
                                                                    {index + 1}
                                                                </div>
                                                                <h4 className="font-semibold text-gray-900">Proceso #{index + 1}</h4>
                                                            </div>
                                                            <Button
                                                                type="button"
                                                                variant="ghost"
                                                                size="sm"
                                                                onClick={() => handleRemoveProcess(process.id)}
                                                                className="text-gray-400 hover:text-red-500 hover:bg-red-50"
                                                            >
                                                                <Trash2 className="w-4 h-4" />
                                                            </Button>
                                                        </div>

                                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                                                            <div className="space-y-1.5 md:col-span-2">
                                                                <Label className="text-xs font-medium text-gray-500">Tipo de Proceso *</Label>
                                                                <SearchableSelect
                                                                    options={procesosOptions.map(p => ({ value: p.id.toString(), label: p.nombre }))}
                                                                    value={process.proceso_id}
                                                                    onValueChange={(val) => handleProcessChange(process.id, "proceso_id", val)}
                                                                    placeholder="Seleccionar..."
                                                                />
                                                            </div>
                                                        </div>

                                                        <div className="grid grid-cols-2 gap-4">
                                                            <div className="space-y-1.5">
                                                                <Label className="text-xs font-medium text-gray-500">Inicio Estimado *</Label>
                                                                <Input
                                                                    type="date"
                                                                    value={process.fecha_inicio.split('T')[0]} // Show only date part
                                                                    onChange={(e) => handleProcessChange(process.id, "fecha_inicio", e.target.value)}
                                                                    className="h-9"
                                                                />
                                                            </div>
                                                            <div className="space-y-1.5">
                                                                <Label className="text-xs font-medium text-gray-500">Fin Estimado *</Label>
                                                                <Input
                                                                    type="date"
                                                                    value={process.fecha_fin.split('T')[0]} // Show only date part
                                                                    onChange={(e) => handleProcessChange(process.id, "fecha_fin", e.target.value)}
                                                                    className="h-9"
                                                                />
                                                            </div>
                                                        </div>
                                                    </CardContent>
                                                </Card>
                                            ))
                                        )}
                                    </div>
                                </TabsContent>
                            </Tabs>
                        </div>

                        <DialogFooter className="p-6 border-t bg-gray-50/50 flex-shrink-0">
                            <div className="flex items-center justify-between w-full">
                                <Button
                                    type="button"
                                    variant="outline"
                                    onClick={handleAttemptClose}
                                    className="h-11 px-8 hover:bg-white hover:text-red-600 hover:border-red-200 transition-colors"
                                >
                                    Cancelar
                                </Button>
                                <div className="flex gap-3">
                                    {activeTab === "procesos" && (
                                        <Button
                                            key="prev-button"
                                            type="button"
                                            variant="outline"
                                            onClick={() => setActiveTab("general")}
                                            className="h-11 px-6"
                                        >
                                            <ArrowLeft className="w-4 h-4 mr-2" />
                                            Anterior
                                        </Button>
                                    )}

                                    <Button
                                        key="submit-button"
                                        type="submit"
                                        disabled={submitting || loading}
                                        className="h-11 px-8 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg shadow-blue-500/30 transition-all hover:scale-[1.02]"
                                    >
                                        {submitting ? (
                                            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                        ) : (
                                            <CheckCircle2 className="mr-2 h-4 w-4" />
                                        )}
                                        {activeTab === "procesos" ? "Crear Orden" : "Siguiente / Crear"}
                                    </Button>
                                </div>
                            </div>
                        </DialogFooter>
                    </form>
                </DialogContent>
            </Dialog >
        </>
    );
}
