"use client";

import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Calendar as CalendarIcon, Loader2, Package, User, Settings, FileText, Plus, Trash2, ArrowRight, ArrowLeft, CheckCircle2, UploadCloud, X, Image as ImageIcon, Layers, Printer } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "sonner";
import { cn, capitalizeName } from "@/lib/utils";
import { SearchableSelect } from "@/components/ui/searchable-select";
import { ConfirmationDialog } from "@/components/ui/confirmation-dialog";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";

import { WorkOrder } from "@/lib/types";
import { API_URL } from "@/config";
import { ProcesosEditor, ProcesoRow } from "@/components/planning/ProcesosEditor";

const getAuthHeaders = (): HeadersInit => {
    if (typeof window === 'undefined') return {};
    const token = localStorage.getItem('access_token');
    return token ? { 'Authorization': `Bearer ${token}` } : {};
};

interface CreateWorkOrderModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSuccess?: () => void;
    orderToEdit?: WorkOrder | null;
}

interface Option {
    id: number;
    nombre: string;
}

interface Maquina {
    id: number;
    nombre: string;
}

interface Articulo {
    id: number;
    cod_articulo: string;
    descripcion: string;
}

interface MateriaPrimaItem {
    id: string; // Temp ID
    codigo: string;
    descripcion: string;
    cantidad: string;
    unidad: string;
    disponible: string;
    en_produccion: string;
    observaciones: string;
    precio: string;
    c_usado: string;
    utilizado: boolean;
    cortes: string;
}

export default function CreateWorkOrderModal({ isOpen, onClose, onSuccess, orderToEdit }: CreateWorkOrderModalProps) {
    const [loading, setLoading] = useState(false);
    const [submitting, setSubmitting] = useState(false);
    const [historialLoading, setHistorialLoading] = useState(false);
    const [activeTab, setActiveTab] = useState("general");
    const [showConfirmSubmit, setShowConfirmSubmit] = useState(false);
    const [showConfirmCancel, setShowConfirmCancel] = useState(false);


    // Form state
    const [generalData, setGeneralData] = useState({
        // numero_orden removed - generated by backend
        cliente: "", // Legacy or display name
        cliente_id: "", // New ID field
        descripcion: "",
        prioridad_id: "",
        articulo_id: "",
        sector_id: "", // Nuevo campo DB
        fecha_prometida: "",
        fecha_entrada: new Date().toISOString().split('T')[0],
        fecha_orden: new Date().toISOString().split('T')[0],
        fecha_entrega: "",
        cantidad_entregada: "",
        reclamo: false,
        finalizadototal: false,
        finalizadoparcial: false,
        id_otvieja: "",
        // Campos "En Desarrollo" (sin db)
        n_ped_l: "",
        n_pedido: "",
        subsector: "",
        requerido_por: "",
        aprobado_por: "",
        remitos_salida: "",
        f_disp_material: "",
        fabricacion: false,
        reparacion: false,
        sin_cargo: false,
        stock: false,
        interno: false,
        revisada: false,
        tercerizado_total: false,
        tercerizado_parcial: false,
        suspendida: false,
        email: false,
        tiene_plano: false,
        programada: false,
        en_proceso: false,
    });

    const [detailsData, setDetailsData] = useState({
        cantidad: "",
        observaciones: "",
        nota_1: "",
        nota_2: "",
        nota_3: "",
    });

    const [materiasPrimasForm, setMateriasPrimasForm] = useState({
        articulo_id: "",
        cantidad: "",
        observaciones: "",
        no_lleva: false
    });

    const [processes, setProcesses] = useState<ProcesoRow[]>([]);
    const [materiasPrimas, setMateriasPrimas] = useState<MateriaPrimaItem[]>([]);
    const [files, setFiles] = useState<File[]>([]);
    const [existingFiles, setExistingFiles] = useState<ExistingFile[]>([]);
    const [deletedFileIds, setDeletedFileIds] = useState<number[]>([]);

    interface ExistingFile {
        id: number;
        nombre: string;
        tipo_archivo: string;
    }

    // Data options
    const [prioridades, setPrioridades] = useState<Option[]>([]);
    const [procesosOptions, setProcesosOptions] = useState<Option[]>([]);
    const [articulos, setArticulos] = useState<Articulo[]>([]);
    const [clientes, setClientes] = useState<Option[]>([]); // New state
    const [operarios, setOperarios] = useState<{ id: number, nombre: string, apellido: string }[]>([]);
    const [maquinarias, setMaquinarias] = useState<Maquina[]>([]);
    const [sectores, setSectores] = useState<Option[]>([]);

    useEffect(() => {
        if (isOpen) {
            fetchData();
            if (activeTab !== "general") setActiveTab("general");

            if (isOpen && orderToEdit) {
                // Populate form with existing data
                console.log("Populating form with:", orderToEdit);
                // Helper to get ID string safely
                const getSafeId = (obj: any) => obj?.id?.toString() || "";

                setGeneralData({
                    cliente: orderToEdit.cliente ? (typeof orderToEdit.cliente === 'object' ? orderToEdit.cliente.nombre : orderToEdit.cliente) || "" : "",
                    cliente_id: getSafeId(orderToEdit.cliente),
                    descripcion: orderToEdit.detalle || orderToEdit.observaciones || "",
                    prioridad_id: getSafeId(orderToEdit.prioridad) || orderToEdit.id_prioridad?.toString() || "1",
                    articulo_id: getSafeId(orderToEdit.articulo) || orderToEdit.id_articulo?.toString() || "",
                    sector_id: getSafeId(orderToEdit.sector) || orderToEdit.id_sector?.toString() || "1",
                    fecha_prometida: orderToEdit.fecha_prometida ? orderToEdit.fecha_prometida.split('T')[0] : "",
                    fecha_entrada: orderToEdit.fecha_entrada ? orderToEdit.fecha_entrada.split('T')[0] : new Date().toISOString().split('T')[0],
                    fecha_orden: orderToEdit.fecha_orden ? orderToEdit.fecha_orden.split('T')[0] : new Date().toISOString().split('T')[0],
                    fecha_entrega: orderToEdit.fecha_entrega ? orderToEdit.fecha_entrega.split('T')[0] : "",
                    cantidad_entregada: orderToEdit.cantidad_entregada?.toString() || "",
                    reclamo: orderToEdit.reclamo === 1 || orderToEdit.reclamo === true,
                    finalizadototal: orderToEdit.finalizadototal === 1 || orderToEdit.finalizadototal === true,
                    finalizadoparcial: orderToEdit.finalizadoparcial === 1 || orderToEdit.finalizadoparcial === true,
                    id_otvieja: orderToEdit.id_otvieja?.toString() || "",
                    // Campos Pronto funcionales
                    n_ped_l: orderToEdit.n_ped_l || "",
                    n_pedido: orderToEdit.n_pedido || "",
                    subsector: orderToEdit.subsector || "",
                    requerido_por: orderToEdit.requerido_por || "",
                    aprobado_por: orderToEdit.aprobado_por || "",
                    remitos_salida: orderToEdit.remitos_salida || "",
                    f_disp_material: orderToEdit.f_disp_material ? orderToEdit.f_disp_material.split('T')[0] : "",
                    fabricacion: orderToEdit.fabricacion === 1 || orderToEdit.fabricacion === true,
                    reparacion: orderToEdit.reparacion === 1 || orderToEdit.reparacion === true,
                    sin_cargo: orderToEdit.sin_cargo === 1 || orderToEdit.sin_cargo === true,
                    stock: orderToEdit.stock === 1 || orderToEdit.stock === true,
                    interno: orderToEdit.interno === 1 || orderToEdit.interno === true,
                    revisada: orderToEdit.revisada === 1 || orderToEdit.revisada === true,
                    tercerizado_total: orderToEdit.tercerizado_total === 1 || orderToEdit.tercerizado_total === true,
                    tercerizado_parcial: orderToEdit.tercerizado_parcial === 1 || orderToEdit.tercerizado_parcial === true,
                    suspendida: orderToEdit.suspendida === 1 || orderToEdit.suspendida === true,
                    email: orderToEdit.email === 1 || orderToEdit.email === true,
                    tiene_plano: orderToEdit.tiene_plano === 1 || orderToEdit.tiene_plano === true,
                    programada: orderToEdit.programada === 1 || orderToEdit.programada === true,
                    en_proceso: orderToEdit.en_proceso === 1 || orderToEdit.en_proceso === true
                });

                setDetailsData({
                    cantidad: orderToEdit.unidades ? orderToEdit.unidades.toString() : "",
                    observaciones: orderToEdit.observaciones || "",
                    nota_1: "",
                    nota_2: "",
                    nota_3: "",
                });

                // Populate processes if they exist
                if (orderToEdit.procesos && orderToEdit.procesos.length > 0) {
                    const mappedProcesses: ProcesoRow[] = orderToEdit.procesos.map(p => ({
                        id: Math.random().toString(36).substr(2, 9), // Temp UI ID
                        proceso_id: p.proceso.id.toString(),
                        tiempo: p.tiempo_proceso ? p.tiempo_proceso.toString() : "",
                        cant_operarios: p.cant_operarios ? p.cant_operarios.toString() : "1",
                        // id_maquinaria puede no estar en el tipo TS todavía; lo leemos defensivo.
                        maquina_id: (p as any).id_maquinaria ? (p as any).id_maquinaria.toString() : "",
                        incluido: true,
                    }));
                    setProcesses(mappedProcesses);
                } else {
                    setProcesses([]);
                }

                // Fetch existing files
                fetch(`${API_URL}/planos/orden/${orderToEdit.id}`, { headers: getAuthHeaders() })
                    .then(async (res) => {
                        if (res.ok) {
                            const data = await res.json();
                            if (data.status && Array.isArray(data.data)) {
                                setExistingFiles(data.data);
                            }
                        }
                    })
                    .catch(err => console.error("Error fetching files:", err));

                // Fetch existing materias primas (orden_trabajo_pieza JOIN pieza)
                fetch(`${API_URL}/ordenes-trabajo-piezas?id_orden_trabajo=${orderToEdit.id}`, { headers: getAuthHeaders() })
                    .then(async (res) => {
                        if (!res.ok) return;
                        const data = await res.json();
                        if (!data.status || !Array.isArray(data.data)) return;
                        const mapped: MateriaPrimaItem[] = data.data.map((p: any) => ({
                            id: p.id?.toString() || Math.random().toString(36).substr(2, 9),
                            codigo: p.cod_pieza || "",
                            descripcion: p.descripcion || "",
                            cantidad: p.cantidad?.toString() || "0",
                            unidad: p.unidad || "",
                            disponible: p.disponible?.toString() || "0",
                            en_produccion: "",
                            observaciones: "",
                            precio: p.unitario?.toString() || "0",
                            c_usado: p.cantusada?.toString() || "0",
                            utilizado: false,
                            cortes: "",
                        }));
                        setMateriasPrimas(mapped);
                    })
                    .catch(err => console.error("Error fetching materias primas:", err));

            } else {
                // Reset if new
                resetForm();
            }
        }
    }, [isOpen, orderToEdit]);

    const fetchData = async () => {
        setLoading(true);
        try {
            const [prioridadesRes, procesosRes, operariosRes, maquinariasRes, articulosRes, clientesRes, sectoresRes] = await Promise.all([
                fetch(`${API_URL}/prioridades`, { headers: getAuthHeaders() }),
                fetch(`${API_URL}/procesos`, { headers: getAuthHeaders() }),
                fetch(`${API_URL}/operarios`, { headers: getAuthHeaders() }),
                fetch(`${API_URL}/maquinarias`, { headers: getAuthHeaders() }),
                fetch(`${API_URL}/articulos`, { headers: getAuthHeaders() }),
                fetch(`${API_URL}/clientes`, { headers: getAuthHeaders() }),
                fetch(`${API_URL}/sectores`, { headers: getAuthHeaders() })
            ]);

            if (prioridadesRes.ok) {
                const data = await prioridadesRes.json();
                const rawData = Array.isArray(data) ? data : (data.data || []);
                setPrioridades(rawData.map((p: any) => ({ id: p.id, nombre: p.descripcion })));
            }
            if (clientesRes.ok) {
                const data = await clientesRes.json();
                const rawData = Array.isArray(data) ? data : (data.data || []);
                setClientes(rawData.map((c: any) => ({ id: c.id, nombre: c.nombre })));
            }
            if (procesosRes.ok) {
                const data = await procesosRes.json();
                setProcesosOptions(Array.isArray(data) ? data : (data.data || []));
            }
            if (operariosRes.ok) {
                const data = await operariosRes.json();
                setOperarios(Array.isArray(data) ? data : (data.data || []));
            }
            if (maquinariasRes.ok) {
                const data = await maquinariasRes.json();
                setMaquinarias(Array.isArray(data) ? data : (data.data || []));
            }
            if (articulosRes.ok) {
                const data = await articulosRes.json();
                setArticulos(Array.isArray(data) ? data : (data.data || []));
            }
            if (sectoresRes.ok) {
                const data = await sectoresRes.json();
                const rawData = Array.isArray(data) ? data : (data.data || []);
                setSectores(rawData.map((s: any) => ({ id: s.id, nombre: s.nombre || s.descripcion })));
            }
        } catch (error) {
            console.error("Error fetching data:", error);
        } finally {
            setLoading(false);
        }
    };

    const handleAddMateriaPrima = () => {
        if (!materiasPrimasForm.articulo_id) {
            toast.error("Seleccione una Materia Prima / Artículo");
            return;
        }

        const selectedArt = articulos.find(a => a.id.toString() === materiasPrimasForm.articulo_id);

        const newMP: MateriaPrimaItem = {
            id: Math.random().toString(36).substr(2, 9),
            codigo: selectedArt?.cod_articulo || "",
            descripcion: selectedArt?.descripcion || "",
            cantidad: materiasPrimasForm.cantidad || "1",
            unidad: "U", // Default
            disponible: "-",
            en_produccion: "-",
            observaciones: materiasPrimasForm.observaciones,
            precio: "-",
            c_usado: "-",
            utilizado: false,
            cortes: "Cortes"
        };

        setMateriasPrimas([...materiasPrimas, newMP]);
        // Reset mini form
        setMateriasPrimasForm({ ...materiasPrimasForm, articulo_id: "", cantidad: "", observaciones: "" });
    };

    const handleRemoveMateriaPrima = (id: string) => {
        setMateriasPrimas(materiasPrimas.filter(p => p.id !== id));
    };

    const validateForm = () => {
        // OTs sincronizadas desde legacy: solo validamos fecha_prometida, lo demás está bloqueado.
        const legacyOT = !!orderToEdit?.id_otvieja;
        if (legacyOT) {
            if (!generalData.fecha_prometida) {
                toast.error("La fecha prometida es obligatoria");
                setActiveTab("general");
                return false;
            }
            return true;
        }

        if (!generalData.cliente_id || !generalData.descripcion || !generalData.prioridad_id || !generalData.articulo_id) {
            toast.error("Por favor completa los campos obligatorios en la pestaña General");
            setActiveTab("general");
            return false;
        }

        // Sólo validamos los procesos tildados ("Va"): los destildados no se guardan.
        const incluidos = processes.filter(p => p.incluido);
        if (incluidos.length === 0) {
            toast.error("Debes agregar al menos un proceso");
            setActiveTab("procesos");
            return false;
        }

        for (const p of incluidos) {
            if (!p.proceso_id || !p.tiempo) {
                toast.error("Por favor completa la información de todos los procesos (incluyendo minutos)");
                setActiveTab("procesos");
                return false;
            }
        }
        return true;
    };

    const handleNextStep = () => {
        if (activeTab === "general") setActiveTab("materias");
        else if (activeTab === "materias") setActiveTab("procesos");
    };

    const handlePrevStep = () => {
        if (activeTab === "procesos") setActiveTab("materias");
        else if (activeTab === "materias") setActiveTab("general");
    }

    // OT proveniente del sistema legacy: solo se puede editar fecha_prometida.
    const isLegacyOT = !!orderToEdit?.id_otvieja;

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // Trigger confirmation if validation passes
        if (validateForm()) {
            setShowConfirmSubmit(true);
        }
    };

    const performSubmission = async () => {
        setSubmitting(true);

        const selectedArticle = articulos.find(a => a.id.toString() === generalData.articulo_id);
        const articleDescription = selectedArticle ? `${selectedArticle.cod_articulo} - ${selectedArticle.descripcion}` : "";

        // Unir las notas en observaciones
        let observacionesUnidas = detailsData.observaciones || articleDescription;
        if (detailsData.nota_1) observacionesUnidas += `\nNota 1: ${detailsData.nota_1}`;
        if (detailsData.nota_2) observacionesUnidas += `\nNota 2: ${detailsData.nota_2}`;
        if (detailsData.nota_3) observacionesUnidas += `\nNota 3: ${detailsData.nota_3}`;

        const fullData = {
            id_otvieja: generalData.id_otvieja ? parseInt(generalData.id_otvieja) : 0, // 0 triggers backend auto-generation
            observaciones: observacionesUnidas,
            detalle: generalData.descripcion,
            id_cliente: parseInt(generalData.cliente_id),
            cliente: clientes.find(c => c.id.toString() === generalData.cliente_id)?.nombre || "",
            unidades: detailsData.cantidad ? parseInt(detailsData.cantidad) : 0,

            id_prioridad: parseInt(generalData.prioridad_id),
            id_sector: generalData.sector_id ? parseInt(generalData.sector_id) : 1,
            id_articulo: parseInt(generalData.articulo_id),

            fecha_orden: generalData.fecha_orden ? new Date(generalData.fecha_orden).toISOString() : new Date().toISOString(),
            fecha_entrada: generalData.fecha_entrada ? new Date(generalData.fecha_entrada).toISOString() : new Date().toISOString(),
            fecha_prometida: generalData.fecha_prometida ? new Date(generalData.fecha_prometida).toISOString() : new Date().toISOString(),
            fecha_entrega: generalData.fecha_entrega ? new Date(generalData.fecha_entrega).toISOString() : null,

            cantidad_entregada: generalData.cantidad_entregada ? parseInt(generalData.cantidad_entregada) : 0,
            reclamo: generalData.reclamo ? 1 : 0,
            finalizadototal: generalData.finalizadototal ? 1 : 0,
            finalizadoparcial: generalData.finalizadoparcial ? 1 : 0,

            // Nuevos Campos "Pronto"
            n_ped_l: generalData.n_ped_l,
            n_pedido: generalData.n_pedido,
            subsector: generalData.subsector,
            requerido_por: generalData.requerido_por,
            aprobado_por: generalData.aprobado_por,
            remitos_salida: generalData.remitos_salida,
            f_disp_material: generalData.f_disp_material ? new Date(generalData.f_disp_material).toISOString() : null,

            fabricacion: generalData.fabricacion,
            reparacion: generalData.reparacion,
            sin_cargo: generalData.sin_cargo,
            stock: generalData.stock,
            interno: generalData.interno,
            revisada: generalData.revisada,
            tercerizado_total: generalData.tercerizado_total,
            tercerizado_parcial: generalData.tercerizado_parcial,
            suspendida: generalData.suspendida,
            email: generalData.email,
            tiene_plano: generalData.tiene_plano,
            programada: generalData.programada,
            en_proceso: generalData.en_proceso,

            // Sólo se guardan los procesos tildados ("Va") con proceso elegido.
            // maquinaria_id se manda como string ('' -> null) para respetar el DTO.
            procesos: processes
                .filter(p => p.incluido && p.proceso_id)
                .map(p => ({
                    proceso_id: parseInt(p.proceso_id),
                    tiempo_proceso: parseInt(p.tiempo) || 0,
                    cant_operarios: parseInt(p.cant_operarios) || 1,
                    maquinaria_id: p.maquina_id ? p.maquina_id : null,
                }))
        };

        try {
            let response;

            if (orderToEdit) {
                // UPDATE (PUT) - Expects JSON
                response = await fetch(`${API_URL}/ordenes/${orderToEdit.id}`, {
                    method: "PUT",
                    headers: {
                        ...getAuthHeaders() as Record<string, string>,
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify(fullData),
                });
            } else {
                // CREATE (POST) - Expects Multipart/Form-Data
                const formData = new FormData();
                formData.append('data', JSON.stringify(fullData));
                files.forEach(file => {
                    formData.append('files', file);
                });

                response = await fetch(`${API_URL}/ordenes`, {
                    method: "POST",
                    headers: getAuthHeaders(),
                    body: formData,
                });
            }

            if (!response.ok) {
                const errorData = await response.json();
                console.error("Error response from backend:", errorData);

                let errorMessage = "Error al crear la orden";

                // Parse standardized backend errors (ResponseDTO)
                if (errorData.errors && Array.isArray(errorData.errors) && errorData.errors.length > 0) {
                    errorMessage = errorData.errors.map((e: any) => e.message).join(", ");
                }
                // Parse standard FastAPI details
                else if (typeof errorData.detail === 'string') {
                    errorMessage = errorData.detail;
                } else if (errorData.detail && Array.isArray(errorData.detail)) {
                    // Pydantic validation errors
                    errorMessage = errorData.detail.map((e: any) => e.msg).join(", ");
                } else if (errorData.message) {
                    errorMessage = errorData.message;
                }

                throw new Error(errorMessage);
            }

            // Handle file updates for EDIT mode
            if (orderToEdit) {
                // 1. Delete removed files
                if (deletedFileIds.length > 0) {
                    await Promise.all(deletedFileIds.map(id =>
                        fetch(`${API_URL}/planos/${id}`, { method: 'DELETE', headers: getAuthHeaders() })
                    ));
                }

                // 2. Upload new files
                if (files.length > 0) {
                    for (const file of files) {
                        const fileData = new FormData();
                        fileData.append('nombre', file.name);
                        fileData.append('tipo_archivo', file.type);
                        fileData.append('id_orden_trabajo', orderToEdit.id.toString());
                        fileData.append('archivo', file);

                        await fetch(`${API_URL}/planos`, {
                            method: "POST",
                            headers: getAuthHeaders(),
                            body: fileData
                        });
                    }
                }
            }

            toast.success(orderToEdit ? "Orden de Trabajo actualizada correctamente" : "Orden de Trabajo creada correctamente");
            onSuccess?.();
            onClose();
            resetForm();
        } catch (error) {
            console.error("Error creating/updating order:", error);
            toast.error(error instanceof Error ? error.message : "Error desconocido al crear la orden");
        } finally {
            setSubmitting(false);
        }
    };

    const resetForm = () => {
        setGeneralData({
            cliente: "", cliente_id: "", descripcion: "", prioridad_id: "", articulo_id: "", sector_id: "", fecha_prometida: "",
            fecha_entrada: new Date().toISOString().split('T')[0], fecha_orden: new Date().toISOString().split('T')[0],
            fecha_entrega: "", cantidad_entregada: "", reclamo: false, finalizadototal: false, finalizadoparcial: false,
            n_ped_l: "", n_pedido: "", subsector: "", requerido_por: "", aprobado_por: "", remitos_salida: "",
            f_disp_material: "", fabricacion: false, reparacion: false, sin_cargo: false, stock: false, interno: false,
            revisada: false, tercerizado_total: false, tercerizado_parcial: false, suspendida: false, email: false, tiene_plano: false,
            programada: false, en_proceso: false, id_otvieja: ""
        });
        setDetailsData({ cantidad: "", observaciones: "", nota_1: "", nota_2: "", nota_3: "" });
        setMateriasPrimasForm({ articulo_id: "", cantidad: "", observaciones: "", no_lleva: false });
        setProcesses([]);
        setMateriasPrimas([]);
        setFiles([]);
        setExistingFiles([]);
        setDeletedFileIds([]);
        setActiveTab("general");
    };

    const handleAttemptClose = () => {
        // Check if form is dirty (has data)
        const isDirty = generalData.cliente_id || generalData.descripcion || processes.length > 0;

        if (isDirty) {
            setShowConfirmCancel(true);
        } else {
            handleClose();
        }
    };

    const handleClose = () => {
        resetForm();
        onClose();
        setActiveTab("general");
    };

    // "Traer historial": trae los procesos de la última OT del mismo producto
    // (artículo = código + descripción) y los carga en el listado, todos tildados.
    const handleTraerHistorial = async () => {
        if (!generalData.articulo_id) {
            toast.error("Elegí primero el producto (artículo) en la pestaña General");
            setActiveTab("general");
            return;
        }
        setHistorialLoading(true);
        try {
            const params = new URLSearchParams({ id_articulo: generalData.articulo_id });
            if (orderToEdit?.id) params.set("excluir_orden_id", orderToEdit.id.toString());
            const res = await fetch(`${API_URL}/ordenes/historial-procesos?${params.toString()}`, { headers: getAuthHeaders() });
            if (!res.ok) throw new Error("request failed");
            const body = await res.json();
            const items = Array.isArray(body?.data) ? body.data : [];
            if (items.length === 0) {
                toast.info("No hay historial de procesos para este producto");
                return;
            }
            const nuevos: ProcesoRow[] = items.map((it: any) => ({
                id: Math.random().toString(36).slice(2),
                proceso_id: it.id_proceso != null ? it.id_proceso.toString() : "",
                tiempo: it.tiempo_proceso != null ? it.tiempo_proceso.toString() : "",
                cant_operarios: it.cant_operarios != null ? it.cant_operarios.toString() : "1",
                maquina_id: it.id_maquinaria ? it.id_maquinaria.toString() : "",
                incluido: true,
            }));
            setProcesses(nuevos);
            toast.success(`Se trajeron ${nuevos.length} procesos del historial. Destildá los que esta vez no van.`);
        } catch (e) {
            console.error(e);
            toast.error("No se pudo traer el historial");
        } finally {
            setHistorialLoading(false);
        }
    };

    // "Imprimir OT": arma una vista imprimible (ventana nueva) con los datos de la
    // orden + procesos + materias primas, y dispara el diálogo de impresión del navegador.
    // Usa el estado actual del formulario, así sirve tanto para una OT existente como para un borrador.
    const handlePrint = () => {
        const esc = (v: unknown) => String(v ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        const fmt = (d?: string) => (d ? new Date(d).toLocaleDateString("es-AR") : "-");
        const cliente = clientes.find(c => c.id.toString() === generalData.cliente_id)?.nombre || generalData.cliente || "-";
        const art = articulos.find(a => a.id.toString() === generalData.articulo_id);
        const articuloLabel = art ? `${art.cod_articulo} — ${art.descripcion}` : "-";
        const prioridad = prioridades.find(p => p.id.toString() === generalData.prioridad_id)?.nombre || "-";
        const sector = sectores.find(s => s.id.toString() === generalData.sector_id)?.nombre || "-";
        const procName = (id: string) => procesosOptions.find(p => p.id.toString() === id)?.nombre || "-";
        const maqName = (id: string) => maquinarias.find(m => m.id.toString() === id)?.nombre || "Sin máquina";

        const procs = processes.filter(p => p.incluido && p.proceso_id);
        // Hoja de procesos (operario): datos planificados + columnas en blanco para
        // la carga real a mano (empleado, horarios, total, obs).
        const procRows = procs.length
            ? procs.map((p, i) => `<tr><td class="c">${i + 1}</td><td>${esc(procName(p.proceso_id))}</td><td>${p.maquina_id ? esc(maqName(p.maquina_id)) : '<span style="color:#999">Sin máquina</span>'}</td><td class="c">${esc(p.tiempo || 0)}</td><td class="fill"></td><td class="fill"></td><td class="fill"></td><td class="fill"></td><td class="fill"></td></tr>`).join("")
            : `<tr><td colspan="9" class="c" style="color:#999">Sin procesos cargados</td></tr>`;

        // Hoja de materias primas (pañol): datos + columna "Retirado" para tildar a mano.
        const mpRows = materiasPrimas.length
            ? materiasPrimas.map(mp => `<tr><td>${esc(mp.codigo)}</td><td>${esc(mp.descripcion)}</td><td class="c">${esc(mp.cantidad)}</td><td class="c">${esc(mp.unidad)}</td><td class="fill c"></td><td class="fill"></td></tr>`).join("")
            : `<tr><td colspan="6" class="c" style="color:#999">Sin materias primas</td></tr>`;

        const otNum = orderToEdit?.id_otvieja || orderToEdit?.id || "Nueva";
        const hoy = new Date().toLocaleDateString("es-AR");
        const logoUrl = `${window.location.origin}/longchamps_logo.png`;
        const encabezado = (titulo: string, subtitulo: string) => `
<div class="head">
  <img class="logo" src="${logoUrl}" alt="Longchamps" onerror="this.style.display='none'">
  <div class="head-c"><div class="empresa">Metalúrgica Longchamps</div><div class="doc">${esc(titulo)}</div></div>
  <div class="head-r"><div class="otn">OT N° ${esc(otNum)}</div><div class="fecha">${esc(subtitulo)}</div></div>
</div>`;
        const html = `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>OT ${esc(otNum)}</title>
<style>
*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#222;margin:0;font-size:12px}
.page{padding:14mm 12mm}.page.break{page-break-after:always}
.head{display:flex;align-items:center;gap:14px;border-bottom:3px solid #1e3a5f;padding-bottom:8px;margin-bottom:12px}
.logo{height:48px;width:auto}.head-c{flex:1}.empresa{font-size:12px;color:#1e3a5f;font-weight:bold;letter-spacing:.5px}
.doc{font-size:20px;font-weight:bold;color:#111}.head-r{text-align:right}.otn{font-size:16px;font-weight:bold}.fecha{font-size:10px;color:#666}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:2px 24px;margin-bottom:10px}
.cell{border-bottom:1px solid #eee;padding:4px 0;display:flex;justify-content:space-between;gap:12px}
.cell .k{color:#888;text-transform:uppercase;font-size:10px;letter-spacing:.5px}.cell .v{font-weight:bold;text-align:right}
h2{font-size:13px;margin:16px 0 6px;border-bottom:2px solid #333;padding-bottom:3px}
table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #bbb;padding:5px 7px;text-align:left;vertical-align:top}
th{background:#eef2f7;text-transform:uppercase;font-size:9px}
td.c,th.c{text-align:center}td.fill{height:30px;background:#fff}
.notas{white-space:pre-wrap;border:1px solid #ccc;padding:8px;border-radius:4px;color:#333;margin-top:4px;min-height:44px}
.pie{margin-top:10px;font-size:9px;color:#999;text-align:center}
@media print{.page{padding:8mm 10mm}}
</style></head><body>

<div class="page break">
${encabezado("Orden de Trabajo — Procesos", `Impreso ${esc(hoy)}`)}
<div class="grid">
<div class="cell"><span class="k">Cliente</span><span class="v">${esc(cliente)}</span></div>
<div class="cell"><span class="k">Prioridad</span><span class="v">${esc(prioridad)}</span></div>
<div class="cell"><span class="k">Producto</span><span class="v">${esc(articuloLabel)}</span></div>
<div class="cell"><span class="k">Sector</span><span class="v">${esc(sector)}</span></div>
<div class="cell"><span class="k">Cantidad</span><span class="v">${esc(detailsData.cantidad || "-")}</span></div>
<div class="cell"><span class="k">N° Pedido</span><span class="v">${esc(generalData.n_pedido || "-")}</span></div>
<div class="cell"><span class="k">F. Entrada</span><span class="v">${fmt(generalData.fecha_entrada)}</span></div>
<div class="cell"><span class="k">F. Prometida</span><span class="v">${fmt(generalData.fecha_prometida)}</span></div>
</div>
<h2>Procesos (planificado + carga real)</h2>
<table><thead><tr><th class="c">#</th><th>Proceso</th><th>Máquina</th><th class="c">Min. plan.</th><th>Empleado</th><th class="c">H. inicio</th><th class="c">H. fin</th><th class="c">Total</th><th>Obs.</th></tr></thead><tbody>${procRows}</tbody></table>
<h2>Nota de taller</h2>
<div class="notas">${esc(detailsData.observaciones || "")}</div>
${generalData.descripcion ? `<h2>Descripción</h2><div class="notas">${esc(generalData.descripcion)}</div>` : ""}
<div class="pie">Hoja de PROCESOS — para el operario</div>
</div>

<div class="page">
${encabezado("Materias Primas", "Retirar en pañol")}
<div class="grid">
<div class="cell"><span class="k">Cliente</span><span class="v">${esc(cliente)}</span></div>
<div class="cell"><span class="k">Producto</span><span class="v">${esc(articuloLabel)}</span></div>
<div class="cell"><span class="k">Cantidad</span><span class="v">${esc(detailsData.cantidad || "-")}</span></div>
<div class="cell"><span class="k">N° Pedido</span><span class="v">${esc(generalData.n_pedido || "-")}</span></div>
</div>
<h2>Materias Primas</h2>
<table><thead><tr><th>Código</th><th>Descripción</th><th class="c">Cant.</th><th class="c">Un.</th><th class="c">Retirado</th><th>Obs.</th></tr></thead><tbody>${mpRows}</tbody></table>
<h2>Observaciones pañol</h2>
<div class="notas"></div>
<div class="pie">Hoja de MATERIAS PRIMAS — para el pañol</div>
</div>

</body></html>`;

        const w = window.open("", "_blank", "width=900,height=700");
        if (!w) {
            toast.error("Habilitá las ventanas emergentes para poder imprimir la OT.");
            return;
        }
        w.document.write(html);
        w.document.close();
        w.focus();
        // Pequeño delay para que el navegador termine de renderizar antes del diálogo de impresión.
        setTimeout(() => w.print(), 250);
    };

    return (
        <>
            <ConfirmationDialog
                isOpen={showConfirmSubmit}
                onClose={() => setShowConfirmSubmit(false)}
                onConfirm={performSubmission}
                title="Crear Orden de Trabajo"
                description="¿Estás seguro de que quieres crear esta Orden de Trabajo? Verificá que todos los datos sean correctos."
                confirmText="Sí, crear orden"
            />

            <ConfirmationDialog
                isOpen={showConfirmCancel}
                onClose={() => setShowConfirmCancel(false)}
                onConfirm={handleClose}
                title="Cancelar Creación"
                description="Si cancelas ahora, perderás todos los datos ingresados. ¿Estás seguro?"
                confirmText="Sí, cancelar"
                cancelText="Volver"
                variant="destructive"
            />

            <Dialog open={isOpen} onOpenChange={(open) => !open && handleAttemptClose()}>

                <DialogContent className="sm:max-w-[95vw] md:max-w-[1200px] bg-white rounded-xl shadow-2xl border-0 h-[85vh] flex flex-col p-0 gap-0 overflow-hidden">
                    <DialogHeader className="p-6 pb-4 border-b bg-white flex-shrink-0">
                        <DialogTitle className="text-2xl font-bold text-gray-900 flex items-center gap-3">
                            <div className="p-2.5 bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl shadow-lg shadow-blue-500/20">
                                <CalendarIcon className="h-6 w-6 text-white" />
                            </div>
                            <div className="flex flex-col">
                                <span>{orderToEdit ? `Editar Orden de Trabajo #${orderToEdit.id_otvieja || orderToEdit.id}` : "Nueva Orden de Trabajo"}</span>
                                <span className="text-sm font-normal text-gray-500 mt-0.5">
                                    {orderToEdit ? "Modifica la información de la OT existente" : "Completa la información para crear una nueva OT"}
                                </span>
                            </div>
                        </DialogTitle>
                    </DialogHeader>

                    <form onSubmit={handleSubmit} className="flex flex-col flex-1 min-h-0">
                        {isLegacyOT && (
                            <div className="mx-6 mt-3 px-3 py-2 bg-amber-50 border border-amber-300 rounded-lg flex items-center gap-2 text-xs text-amber-800">
                                <span className="text-amber-600 text-sm leading-none">⚠️</span>
                                <span><b className="text-amber-900">OT del sistema viejo:</b> solo se puede modificar la <b>fecha prometida</b>; el resto se actualiza automáticamente desde la base original.</span>
                            </div>
                        )}
                        <div className="flex-1 overflow-y-auto px-6 py-4 relative">
                            <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
                                <TabsList className="grid w-full grid-cols-3 mb-4 bg-gray-100/50 p-1 rounded-xl sticky top-0 z-10 backdrop-blur-sm">
                                    <TabsTrigger value="general" className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm data-[state=active]:text-blue-600 transition-all text-xs md:text-sm">
                                        <FileText size={16} className="mr-1 md:mr-2" />
                                        1. Información General
                                    </TabsTrigger>
                                    <TabsTrigger value="materias" className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm data-[state=active]:text-blue-600 transition-all text-xs md:text-sm">
                                        <Layers size={16} className="mr-1 md:mr-2" />
                                        2. Materias Primas
                                    </TabsTrigger>
                                    <TabsTrigger value="procesos" className="rounded-lg data-[state=active]:bg-white data-[state=active]:shadow-sm data-[state=active]:text-blue-600 transition-all text-xs md:text-sm">
                                        <Settings size={16} className="mr-1 md:mr-2" />
                                        3. Procesos (Opcional)
                                    </TabsTrigger>
                                </TabsList>

                                {/* Tab: General */}
                                <TabsContent value="general" className="space-y-4 mt-0 animate-in fade-in-50 slide-in-from-left-2 duration-300">
                                    <div className="grid grid-cols-1 md:grid-cols-4 gap-x-4 gap-y-2">
                                        {/* Section: Identification */}
                                        <div className="md:col-span-4 flex items-center gap-2 mb-1">
                                            <div className="h-px flex-1 bg-gray-100"></div>
                                            <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest px-2">Identificación</span>
                                            <div className="h-px flex-1 bg-gray-100"></div>
                                        </div>
                                        
                                        <div className="space-y-1.5">
                                            <Label htmlFor="id_otvieja" className="text-[11px] font-bold text-blue-600 uppercase">Nº OT Vieja</Label>
                                            <Input id="id_otvieja" disabled={isLegacyOT} value={generalData.id_otvieja} onChange={(e) => setGeneralData({ ...generalData, id_otvieja: e.target.value })} className="h-8 text-sm border-blue-200 focus:ring-blue-500 font-mono font-bold" placeholder="No especificado" />
                                        </div>
                                        <div className="space-y-1.5">
                                            <Label htmlFor="n_pedido" className="text-[11px] font-bold text-gray-500 uppercase">N° Pedido</Label>
                                            <Input id="n_pedido" disabled={isLegacyOT} value={generalData.n_pedido} onChange={(e) => setGeneralData({ ...generalData, n_pedido: e.target.value })} className="h-8 text-sm" placeholder="No especificado" />
                                        </div>
                                        <div className="space-y-1.5">
                                            <Label htmlFor="n_ped_l" className="text-[11px] font-bold text-gray-500 uppercase">N° Ped L</Label>
                                            <Input id="n_ped_l" disabled={isLegacyOT} value={generalData.n_ped_l} onChange={(e) => setGeneralData({ ...generalData, n_ped_l: e.target.value })} className="h-8 text-sm" placeholder="No especificado" />
                                        </div>
                                        <div className="space-y-1.5">
                                            <Label htmlFor="prioridad" className="text-[11px] font-bold text-gray-400 uppercase">Prioridad <span className="text-red-500">*</span></Label>
                                            <SearchableSelect disabled={isLegacyOT} options={prioridades.map(p => ({ value: p.id.toString(), label: p.nombre }))} value={generalData.prioridad_id} onValueChange={(val) => setGeneralData({ ...generalData, prioridad_id: val })} placeholder="No especificado" className="h-8" />
                                        </div>

                                        <div className="md:col-span-2 space-y-1.5">
                                            <Label htmlFor="cliente" className="text-[11px] font-bold text-gray-400 uppercase">Cliente <span className="text-red-500">*</span></Label>
                                            <SearchableSelect disabled={isLegacyOT} options={clientes.map(c => ({ value: c.id.toString(), label: c.nombre }))} value={generalData.cliente_id} onValueChange={(val) => setGeneralData({ ...generalData, cliente_id: val })} placeholder="No especificado" className="h-8" />
                                        </div>
                                        <div className="space-y-1.5">
                                            <Label htmlFor="sector" className="text-[11px] font-bold text-gray-400 uppercase">Sector <span className="text-red-500">*</span></Label>
                                            <SearchableSelect disabled={isLegacyOT} options={sectores.map(s => ({ value: s.id.toString(), label: s.nombre }))} value={generalData.sector_id} onValueChange={(val) => setGeneralData({ ...generalData, sector_id: val })} placeholder="No especificado" className="h-8" />
                                        </div>
                                        <div className="space-y-1.5">
                                            <Label htmlFor="subsector" className="text-[11px] font-bold text-gray-400 uppercase">SubSector</Label>
                                            <Input id="subsector" disabled={isLegacyOT} value={generalData.subsector} onChange={(e) => setGeneralData({ ...generalData, subsector: e.target.value })} className="h-8 text-sm" placeholder="No especificado" />
                                        </div>

                                        {/* Section: Logistics & Quantities */}
                                        <div className="md:col-span-4 flex items-center gap-2 mb-1 mt-1">
                                            <div className="h-px flex-1 bg-gray-100"></div>
                                            <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest px-2">Logística y Cantidades</span>
                                            <div className="h-px flex-1 bg-gray-100"></div>
                                        </div>

                                        <div className="space-y-1.5">
                                            <Label htmlFor="cantidad" className="text-[11px] font-bold text-gray-400 uppercase">Cant Fabricar</Label>
                                            <Input id="cantidad" disabled={isLegacyOT} type="number" value={detailsData.cantidad} onChange={(e) => setDetailsData({ ...detailsData, cantidad: e.target.value })} className="h-8 text-sm font-bold text-blue-700" />
                                        </div>
                                        <div className="space-y-1.5">
                                            <Label htmlFor="cantidad_entregada" className="text-[11px] font-bold text-gray-400 uppercase">Cant Entregada</Label>
                                            <Input id="cantidad_entregada" disabled={isLegacyOT} type="number" value={generalData.cantidad_entregada} onChange={(e) => setGeneralData({ ...generalData, cantidad_entregada: e.target.value })} className="h-8 text-sm" />
                                        </div>
                                        <div className="space-y-1.5">
                                            <Label htmlFor="requerido_por" className="text-[11px] font-bold text-gray-400 uppercase">Requerido por</Label>
                                            <Input id="requerido_por" disabled={isLegacyOT} value={generalData.requerido_por} onChange={(e) => setGeneralData({ ...generalData, requerido_por: e.target.value })} className="h-8 text-sm" placeholder="No especificado" />
                                        </div>
                                        <div className="space-y-1.5">
                                            <Label htmlFor="aprobado_por" className="text-[11px] font-bold text-gray-400 uppercase">Aprobado por</Label>
                                            <Input id="aprobado_por" disabled={isLegacyOT} value={generalData.aprobado_por} onChange={(e) => setGeneralData({ ...generalData, aprobado_por: e.target.value })} className="h-8 text-sm" placeholder="No especificado" />
                                        </div>

                                        {/* Product Full Width */}
                                        <div className="md:col-span-4 space-y-1.5">
                                            <Label htmlFor="articulo" className="text-[11px] font-bold text-gray-400 uppercase">Producto / Artículo <span className="text-red-500">*</span></Label>
                                            <SearchableSelect disabled={isLegacyOT} options={articulos.map(a => ({ value: a.id.toString(), label: `${a.cod_articulo} - ${a.descripcion}` }))} value={generalData.articulo_id} onValueChange={(val) => setGeneralData({ ...generalData, articulo_id: val })} placeholder="No especificado" className="h-8" />
                                        </div>

                                        {/* Section: Dates */}
                                        <div className="md:col-span-4 flex items-center gap-2 mb-1 mt-1">
                                            <div className="h-px flex-1 bg-gray-100"></div>
                                            <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest px-2">Fechas Clave</span>
                                            <div className="h-px flex-1 bg-gray-100"></div>
                                        </div>

                                        <div className="space-y-1.5">
                                            <Label htmlFor="fecha_orden" className="text-[11px] font-bold text-gray-400 uppercase">Fecha Orden</Label>
                                            <Input id="fecha_orden" disabled={isLegacyOT} type="date" value={generalData.fecha_orden} onChange={(e) => setGeneralData({ ...generalData, fecha_orden: e.target.value })} className="h-8 text-sm" />
                                        </div>
                                        <div className="space-y-1.5">
                                            <Label htmlFor="fecha_entrada" className="text-[11px] font-bold text-gray-400 uppercase">Fecha Entrada</Label>
                                            <Input id="fecha_entrada" disabled={isLegacyOT} type="date" value={generalData.fecha_entrada} onChange={(e) => setGeneralData({ ...generalData, fecha_entrada: e.target.value })} className="h-8 text-sm" />
                                        </div>
                                        <div className="space-y-1.5">
                                            <Label htmlFor="fecha_prometida" className="text-[11px] font-bold text-blue-600 uppercase font-black">F. Prometida</Label>
                                            <Input id="fecha_prometida" type="date" value={generalData.fecha_prometida} onChange={(e) => setGeneralData({ ...generalData, fecha_prometida: e.target.value })} className={cn("h-8 text-sm border-blue-200", isLegacyOT && "ring-2 ring-blue-300 ring-offset-1 bg-blue-50/40")} />
                                        </div>
                                        <div className="space-y-1.5">
                                            <Label htmlFor="fecha_entrega" className="text-[11px] font-bold text-gray-400 uppercase">F. Entrega Real</Label>
                                            <Input id="fecha_entrega" disabled={isLegacyOT} type="date" value={generalData.fecha_entrega} onChange={(e) => setGeneralData({ ...generalData, fecha_entrega: e.target.value })} className="h-8 text-sm" />
                                        </div>

                                        <div className="space-y-1.5">
                                            <Label htmlFor="f_disp_material" className="text-[11px] font-bold text-gray-400 uppercase">F. Disp Mat</Label>
                                            <Input id="f_disp_material" disabled={isLegacyOT} type="date" value={generalData.f_disp_material} onChange={(e) => setGeneralData({ ...generalData, f_disp_material: e.target.value })} className="h-8 text-sm" />
                                        </div>
                                        <div className="md:col-span-3 space-y-1.5">
                                            <Label htmlFor="remitos_salida" className="text-[11px] font-bold text-gray-400 uppercase">Remitos Salida</Label>
                                            <Input id="remitos_salida" disabled={isLegacyOT} value={generalData.remitos_salida} onChange={(e) => setGeneralData({ ...generalData, remitos_salida: e.target.value })} className="h-8 text-sm" placeholder="No especificado" />
                                        </div>

                                        {/* Section: Flags (Compact) */}
                                        <div className="md:col-span-4 grid grid-cols-2 md:grid-cols-4 gap-2 p-2.5 border border-gray-100 rounded-xl bg-gray-50/30 mt-1">
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-gray-100/50 px-2 py-1 rounded border border-transparent transition-colors w-full h-8">
                                                <Checkbox id="fabricacion" disabled={isLegacyOT} checked={generalData.fabricacion} onCheckedChange={(c) => setGeneralData({ ...generalData, fabricacion: !!c })} /> 
                                                <span className="text-xs text-gray-600 font-medium tracking-tight">Fabricación</span>
                                            </Label>
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-gray-100/50 px-2 py-1 rounded border border-transparent transition-colors w-full h-8">
                                                <Checkbox id="reparacion" disabled={isLegacyOT} checked={generalData.reparacion} onCheckedChange={(c) => setGeneralData({ ...generalData, reparacion: !!c })} /> 
                                                <span className="text-xs text-gray-600 font-medium tracking-tight">Reparación</span>
                                            </Label>
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-gray-100/50 px-2 py-1 rounded border border-transparent transition-colors w-full h-8">
                                                <Checkbox id="stock" disabled={isLegacyOT} checked={generalData.stock} onCheckedChange={(c) => setGeneralData({ ...generalData, stock: !!c })} /> 
                                                <span className="text-xs text-gray-600 font-medium tracking-tight">Stock</span>
                                            </Label>
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-gray-100/50 px-2 py-1 rounded border border-transparent transition-colors w-full h-8">
                                                <Checkbox id="interno" disabled={isLegacyOT} checked={generalData.interno} onCheckedChange={(c) => setGeneralData({ ...generalData, interno: !!c })} /> 
                                                <span className="text-xs text-gray-600 font-medium tracking-tight">Interno</span>
                                            </Label>
                                            
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-gray-100/50 px-2 py-1 rounded border border-transparent transition-colors w-full h-8">
                                                <Checkbox id="tercerizado_total" disabled={isLegacyOT} checked={generalData.tercerizado_total} onCheckedChange={(c) => setGeneralData({ ...generalData, tercerizado_total: !!c })} /> 
                                                <span className="text-xs text-gray-600 font-medium tracking-tight">Terc. Total</span>
                                            </Label>
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-gray-100/50 px-2 py-1 rounded border border-transparent transition-colors w-full h-8">
                                                <Checkbox id="tercerizado_parcial" disabled={isLegacyOT} checked={generalData.tercerizado_parcial} onCheckedChange={(c) => setGeneralData({ ...generalData, tercerizado_parcial: !!c })} /> 
                                                <span className="text-xs text-gray-600 font-medium tracking-tight">Terc. Parcial</span>
                                            </Label>
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-gray-100/50 px-2 py-1 rounded border border-transparent transition-colors w-full h-8">
                                                <Checkbox id="email" disabled={isLegacyOT} checked={generalData.email} onCheckedChange={(c) => setGeneralData({ ...generalData, email: !!c })} /> 
                                                <span className="text-xs text-gray-600 font-medium tracking-tight">Email</span>
                                            </Label>
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-orange-50 px-2 py-1 rounded border border-transparent transition-colors text-orange-600 font-bold w-full h-8">
                                                <Checkbox id="reclamo" disabled={isLegacyOT} className="border-orange-500 data-[state=checked]:bg-orange-500" checked={generalData.reclamo} onCheckedChange={(c) => setGeneralData({ ...generalData, reclamo: !!c })} /> 
                                                <span className="text-xs uppercase">Reclamo</span>
                                            </Label>
                                            
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-red-50 px-2 py-1 rounded border border-transparent transition-colors text-red-600 font-bold w-full h-8">
                                                <Checkbox id="suspendida" disabled={isLegacyOT} className="border-red-600 data-[state=checked]:bg-red-600" checked={generalData.suspendida} onCheckedChange={(c) => setGeneralData({ ...generalData, suspendida: !!c })} /> 
                                                <span className="text-xs uppercase">Suspendida</span>
                                            </Label>
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-gray-100/50 px-2 py-1 rounded border border-transparent transition-colors w-full h-8">
                                                <Checkbox id="finalizadoparcial" disabled={isLegacyOT} checked={generalData.finalizadoparcial} onCheckedChange={(c) => setGeneralData({ ...generalData, finalizadoparcial: !!c })} /> 
                                                <span className="text-xs text-gray-800 font-bold">Fin. Parcial</span>
                                            </Label>
                                            <Label className="md:col-span-2 flex items-center space-x-2 bg-green-50 px-2 py-1 rounded border border-green-200 cursor-pointer hover:bg-green-100 transition-colors w-full h-8">
                                                <Checkbox id="finalizadototal" disabled={isLegacyOT} checked={generalData.finalizadototal} onCheckedChange={(c) => setGeneralData({ ...generalData, finalizadototal: !!c })} /> 
                                                <span className="text-xs font-bold text-green-700 uppercase tracking-tighter truncate">Entrega Completa (Total)</span>
                                            </Label>
                                        </div>

                                        {/* Status block (Row 7) */}
                                        <div className="md:col-span-4 flex items-center justify-between gap-4 py-2 border-t border-gray-100 mt-1">
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-gray-50 p-1 rounded transition-colors group">
                                                <Checkbox id="tiene_plano" disabled={isLegacyOT} checked={generalData.tiene_plano} onCheckedChange={(c) => setGeneralData({ ...generalData, tiene_plano: !!c })} /> 
                                                <span className="text-xs font-medium text-gray-500 group-hover:text-gray-700">Tiene Plano</span>
                                            </Label>
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-gray-50 p-1 rounded transition-colors group">
                                                <Checkbox id="programada" disabled={isLegacyOT} checked={generalData.programada} onCheckedChange={(c) => setGeneralData({ ...generalData, programada: !!c })} /> 
                                                <span className="text-xs font-medium text-gray-500 group-hover:text-gray-700">Programada</span>
                                            </Label>
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-gray-50 p-1 rounded transition-colors group">
                                                <Checkbox id="en_proceso" disabled={isLegacyOT} checked={generalData.en_proceso} onCheckedChange={(c) => setGeneralData({ ...generalData, en_proceso: !!c })} /> 
                                                <span className="text-xs font-medium text-gray-500 group-hover:text-gray-700">En Proceso</span>
                                            </Label>
                                            <Label className="flex items-center space-x-2 cursor-pointer hover:bg-gray-50 p-1 rounded transition-colors group">
                                                <Checkbox id="revisada" disabled={isLegacyOT} checked={generalData.revisada} onCheckedChange={(c) => setGeneralData({ ...generalData, revisada: !!c })} /> 
                                                <span className="text-xs font-medium text-gray-500 group-hover:text-gray-700">Revisada</span>
                                            </Label>
                                        </div>

                                        {/* Textareas (Compact Row 8) */}
                                        <div className="md:col-span-2 space-y-1.5">
                                            <Label htmlFor="descripcion" className="text-[11px] font-bold text-gray-600 uppercase">Info Gral / Descripción *</Label>
                                            <Textarea id="descripcion" disabled={isLegacyOT} value={generalData.descripcion} onChange={(e) => setGeneralData({ ...generalData, descripcion: e.target.value })} className="h-16 min-h-[60px] text-sm bg-white" required />
                                        </div>
                                        <div className="md:col-span-2 space-y-1.5">
                                            <Label htmlFor="nota_taller" className="text-[11px] font-bold text-gray-600 uppercase">Nota de Taller</Label>
                                            <Textarea id="nota_taller" disabled={isLegacyOT} value={detailsData.observaciones} onChange={(e) => setDetailsData({ ...detailsData, observaciones: e.target.value })} className="h-16 min-h-[60px] text-sm bg-white" />
                                        </div>
                                        
                                        <div className="md:col-span-4 grid grid-cols-3 gap-3">
                                            <div className="space-y-1">
                                                <Label htmlFor="nota_1" className="text-[9px] font-bold text-gray-400 flex items-center justify-between uppercase">Nota 1</Label>
                                                <Input id="nota_1" disabled={isLegacyOT} value={detailsData.nota_1} onChange={(e) => setDetailsData({ ...detailsData, nota_1: e.target.value })} className="h-7 text-xs bg-gray-50/50" />
                                            </div>
                                            <div className="space-y-1">
                                                <Label htmlFor="nota_2" className="text-[9px] font-bold text-gray-400 flex items-center justify-between uppercase">Nota 2</Label>
                                                <Input id="nota_2" disabled={isLegacyOT} value={detailsData.nota_2} onChange={(e) => setDetailsData({ ...detailsData, nota_2: e.target.value })} className="h-7 text-xs bg-gray-50/50" />
                                            </div>
                                            <div className="space-y-1">
                                                <Label htmlFor="nota_3" className="text-[9px] font-bold text-gray-400 flex items-center justify-between uppercase">Nota 3</Label>
                                                <Input id="nota_3" disabled={isLegacyOT} value={detailsData.nota_3} onChange={(e) => setDetailsData({ ...detailsData, nota_3: e.target.value })} className="h-7 text-xs bg-gray-50/50" />
                                            </div>
                                        </div>
                                    </div>

                                    <div className="space-y-2 pt-3">
                                        <Label className="text-sm font-semibold text-gray-700">
                                            Archivos Adjuntos (Planos, Especificaciones)
                                        </Label>
                                        {/* Dynamic Upload Box */}
                                        <div
                                            className={cn(
                                                "border-2 border-dashed border-gray-200 rounded-xl transition-all hover:border-blue-400 hover:bg-blue-50/30 group cursor-pointer relative",
                                                (existingFiles.length > 0 || files.length > 0)
                                                    ? "p-3 flex items-center justify-between gap-4"
                                                    : "p-6 text-center"
                                            )}
                                        >
                                            <input
                                                type="file"
                                                multiple
                                                accept="image/*,.pdf"
                                                disabled={isLegacyOT}
                                                className={cn(
                                                    "absolute inset-0 w-full h-full opacity-0 z-10",
                                                    isLegacyOT ? "cursor-not-allowed" : "cursor-pointer"
                                                )}
                                                onChange={(e) => {
                                                    if (e.target.files) {
                                                        const newFiles = Array.from(e.target.files);
                                                        setFiles(prev => [...prev, ...newFiles]);
                                                    }
                                                }}
                                            />

                                            {(existingFiles.length > 0 || files.length > 0) ? (
                                                <>
                                                    <div className="flex items-center gap-3">
                                                        <div className="p-2 bg-blue-50 text-blue-600 rounded-full group-hover:scale-105 transition-transform">
                                                            <UploadCloud className="w-5 h-5" />
                                                        </div>
                                                        <div className="text-sm text-gray-600 text-left">
                                                            <span className="font-semibold text-blue-600">Agregar más archivos</span>
                                                            <p className="text-xs text-gray-400">PDF, PNG, JPG</p>
                                                        </div>
                                                    </div>
                                                    <div className="pr-2">
                                                        <Plus className="w-5 h-5 text-gray-400 group-hover:text-blue-500" />
                                                    </div>
                                                </>
                                            ) : (
                                                <div className="flex flex-col items-center gap-2 pointer-events-none">
                                                    <div className="p-3 bg-blue-50 text-blue-600 rounded-full group-hover:scale-110 transition-transform">
                                                        <UploadCloud className="w-6 h-6" />
                                                    </div>
                                                    <div className="text-sm text-gray-600">
                                                        <span className="font-semibold text-blue-600">Haz clic para subir</span> o arrastra y suelta
                                                    </div>
                                                    <p className="text-xs text-gray-400">PDF, PNG, JPG (máx. 10MB)</p>
                                                </div>
                                            )}
                                        </div>

                                        {(existingFiles.length > 0 || files.length > 0) && (
                                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-4">
                                                {/* Existing Files */}
                                                {existingFiles.map((file) => (
                                                    <div key={`existing-${file.id}`} className="flex items-center justify-between p-3 bg-blue-50/50 border border-blue-100 rounded-lg group hover:border-blue-300 transition-all">
                                                        <div className="flex items-center gap-3 overflow-hidden">
                                                            <div className="p-2 bg-white rounded-md border border-gray-100 text-gray-500">
                                                                {file.tipo_archivo.includes('pdf') || file.nombre.endsWith('.pdf') ? (
                                                                    <FileText className="w-4 h-4 text-red-500" />
                                                                ) : (
                                                                    <ImageIcon className="w-4 h-4 text-blue-500" />
                                                                )}
                                                            </div>
                                                            <div className="flex flex-col min-w-0">
                                                                <a
                                                                    href={`${API_URL}/planos/${file.id}/archivo?download=true`}
                                                                    target="_blank"
                                                                    rel="noopener noreferrer"
                                                                    className="text-sm font-medium text-gray-700 truncate hover:text-blue-600 hover:underline"
                                                                >
                                                                    {file.nombre}
                                                                </a>
                                                                <span className="text-xs text-gray-400">Existente</span>
                                                            </div>
                                                        </div>
                                                        {!isLegacyOT && (
                                                            <Button
                                                                type="button"
                                                                variant="ghost"
                                                                size="icon"
                                                                onClick={() => {
                                                                    setDeletedFileIds(prev => [...prev, file.id]);
                                                                    setExistingFiles(prev => prev.filter(f => f.id !== file.id));
                                                                }}
                                                                className="h-8 w-8 text-gray-400 hover:text-red-500 hover:bg-red-50"
                                                            >
                                                                <Trash2 className="w-4 h-4" />
                                                            </Button>
                                                        )}
                                                    </div>
                                                ))}

                                                {/* New Files */}
                                                {files.map((file, index) => (
                                                    <div key={index} className="flex items-center justify-between p-3 bg-gray-50 border border-gray-100 rounded-lg group hover:border-blue-200 transition-all">
                                                        <div className="flex items-center gap-3 overflow-hidden">
                                                            <div className="p-2 bg-white rounded-md border border-gray-100 text-gray-500">
                                                                {file.type.includes('pdf') ? (
                                                                    <FileText className="w-4 h-4 text-red-500" />
                                                                ) : (
                                                                    <ImageIcon className="w-4 h-4 text-blue-500" />
                                                                )}
                                                            </div>
                                                            <div className="flex flex-col min-w-0">
                                                                <span className="text-sm font-medium text-gray-700 truncate">{file.name}</span>
                                                                <span className="text-xs text-gray-400">{(file.size / 1024 / 1024).toFixed(2)} MB</span>
                                                            </div>
                                                        </div>
                                                        <Button
                                                            type="button"
                                                            variant="ghost"
                                                            size="icon"
                                                            onClick={() => setFiles(files.filter((_, i) => i !== index))}
                                                            className="h-8 w-8 text-gray-400 hover:text-red-500 hover:bg-red-50"
                                                        >
                                                            <X className="w-4 h-4" />
                                                        </Button>
                                                    </div>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                </TabsContent>

                                {/* Tab: Materias Primas */}
                                <TabsContent value="materias" className="space-y-4 mt-0 animate-in fade-in-50 slide-in-from-right-2 duration-300">
                                    <div className="flex flex-col gap-3">
                                        <div className="flex items-center justify-between">
                                            <div>
                                                <h3 className="text-base font-semibold text-gray-900">Materias Primas</h3>
                                                <p className="text-xs text-gray-500">Administra los materiales necesarios para esta orden</p>
                                            </div>
                                        </div>

                                        {/* Upper Form (oculto si la OT viene del legacy) */}
                                        {!isLegacyOT && (
                                            <div className="grid grid-cols-1 md:grid-cols-12 gap-4 bg-gray-50/50 p-4 rounded-xl border border-gray-100 items-end">
                                                <div className="md:col-span-5 space-y-1.5">
                                                    <Label className="text-xs font-semibold text-gray-600">M. Primas</Label>
                                                    <SearchableSelect options={articulos.map(a => ({ value: a.id.toString(), label: `${a.cod_articulo} - ${a.descripcion}` }))} value={materiasPrimasForm.articulo_id} onValueChange={(val) => setMateriasPrimasForm({ ...materiasPrimasForm, articulo_id: val })} placeholder="Seleccione material" />
                                                </div>
                                                <div className="md:col-span-2 space-y-1.5">
                                                    <Label className="text-xs font-semibold text-gray-600">Cantidad</Label>
                                                    <Input type="number" value={materiasPrimasForm.cantidad} onChange={(e) => setMateriasPrimasForm({ ...materiasPrimasForm, cantidad: e.target.value })} className="h-9" placeholder="1" />
                                                </div>
                                                <div className="md:col-span-4 space-y-1.5">
                                                    <Label className="text-xs font-semibold text-gray-600">Obs.</Label>
                                                    <Input value={materiasPrimasForm.observaciones} onChange={(e) => setMateriasPrimasForm({ ...materiasPrimasForm, observaciones: e.target.value })} className="h-9" placeholder="Observaciones..." />
                                                </div>
                                                <div className="md:col-span-1">
                                                    <Button type="button" onClick={handleAddMateriaPrima} className="w-full h-9 bg-blue-50 text-blue-600 hover:bg-blue-100 border border-blue-200">
                                                        Agregar
                                                    </Button>
                                                </div>
                                            </div>
                                        )}

                                        {/* Table */}
                                        <div className="border border-gray-200 rounded-xl overflow-hidden shadow-sm overflow-x-auto bg-white">
                                            <table className="w-full text-sm text-left relative">
                                                <thead className="text-xs text-gray-600 bg-gray-50/80 border-b border-gray-200 uppercase whitespace-nowrap">
                                                    <tr>
                                                        <th className="px-3 py-2">Código</th>
                                                        <th className="px-3 py-2">Descripción</th>
                                                        <th className="px-3 py-2">Cant</th>
                                                        <th className="px-3 py-2">UN</th>
                                                        <th className="px-3 py-2">Disponible</th>
                                                        <th className="px-3 py-2">En Prod.</th>
                                                        <th className="px-3 py-2 w-32">Obs</th>
                                                        <th className="px-3 py-2">Precio</th>
                                                        <th className="px-3 py-2">C. Usado</th>
                                                        <th className="px-3 py-2 text-center">Utiliz.</th>
                                                        <th className="px-3 py-2 text-center">Cortes</th>
                                                        <th className="px-2 py-2 text-center"></th>
                                                    </tr>
                                                </thead>
                                                <tbody className="divide-y divide-gray-100">
                                                    {materiasPrimas.length === 0 ? (
                                                        <tr>
                                                            <td colSpan={12} className="px-4 py-8 text-center text-gray-400">
                                                                No se agregaron materias primas.
                                                            </td>
                                                        </tr>
                                                    ) : (
                                                        materiasPrimas.map((mp, index) => (
                                                            <tr key={mp.id} className="hover:bg-gray-50/50 transition-colors group">
                                                                <td className="px-3 py-2 font-medium">{mp.codigo}</td>
                                                                <td className="px-3 py-2 truncate max-w-[150px]" title={mp.descripcion}>{mp.descripcion}</td>
                                                                <td className="px-3 py-2">{mp.cantidad}</td>
                                                                <td className="px-3 py-2">{mp.unidad}</td>
                                                                <td className="px-3 py-2 text-gray-500">{mp.disponible}</td>
                                                                <td className="px-3 py-2 text-gray-500">{mp.en_produccion}</td>
                                                                <td className="px-3 py-2 truncate max-w-[100px] text-gray-500" title={mp.observaciones}>{mp.observaciones}</td>
                                                                <td className="px-3 py-2 text-gray-500">{mp.precio}</td>
                                                                <td className="px-3 py-2 text-gray-500">{mp.c_usado}</td>
                                                                <td className="px-3 py-2 text-center">
                                                                    <Checkbox disabled={isLegacyOT} checked={mp.utilizado} onCheckedChange={(c) => {
                                                                        const copy = [...materiasPrimas];
                                                                        copy[index].utilizado = !!c;
                                                                        setMateriasPrimas(copy);
                                                                    }} />
                                                                </td>
                                                                <td className="px-3 py-2">
                                                                    <Input disabled={isLegacyOT} className="h-7 w-20 text-xs text-center" value={mp.cortes} onChange={(e) => {
                                                                        const copy = [...materiasPrimas];
                                                                        copy[index].cortes = e.target.value;
                                                                        setMateriasPrimas(copy);
                                                                    }} />
                                                                </td>
                                                                <td className="px-2 py-2 text-center">
                                                                    {!isLegacyOT && (
                                                                        <Button type="button" variant="ghost" size="sm" onClick={() => handleRemoveMateriaPrima(mp.id)} className="h-7 w-7 p-0 text-gray-400 hover:text-red-500">
                                                                            <Trash2 className="w-4 h-4" />
                                                                        </Button>
                                                                    )}
                                                                </td>
                                                            </tr>
                                                        ))
                                                    )}
                                                </tbody>
                                            </table>
                                        </div>

                                        {/* Bottom Control */}
                                        <div className="flex items-center space-x-2 pt-3 border-t border-gray-100">
                                            <Checkbox id="no_lleva_mp" disabled={isLegacyOT} checked={materiasPrimasForm.no_lleva} onCheckedChange={(c) => setMateriasPrimasForm({ ...materiasPrimasForm, no_lleva: !!c })} />
                                            <Label htmlFor="no_lleva_mp" className="text-sm font-medium text-gray-700 cursor-pointer uppercase">NO LLEVA MATERIAS PRIMAS</Label>
                                        </div>
                                    </div>
                                </TabsContent>

                                {/* Tab: Procesos */}
                                <TabsContent value="procesos" className="space-y-4 mt-0 animate-in fade-in-50 slide-in-from-right-2 duration-300">
                                    <div className="space-y-1 mb-1">
                                        <h3 className="text-lg font-semibold text-gray-900">Procesos de la Orden</h3>
                                        <p className="text-sm text-gray-500">
                                            Elegí proceso, máquina, minutos y cantidad de empleados. Destildá los que esta vez no van (opcional).
                                        </p>
                                    </div>

                                    <ProcesosEditor
                                        rows={processes}
                                        onChange={setProcesses}
                                        procesos={procesosOptions}
                                        maquinarias={maquinarias}
                                        disabled={isLegacyOT}
                                        onTraerHistorial={isLegacyOT ? undefined : handleTraerHistorial}
                                        historialLoading={historialLoading}
                                    />
                                </TabsContent>
                            </Tabs>
                        </div>

                        <DialogFooter className="px-6 py-3 border-t bg-gray-50/50 flex-shrink-0">
                            <div className="flex items-center justify-between w-full">
                                <div className="flex items-center gap-3">
                                    <Button
                                        type="button"
                                        variant="outline"
                                        onClick={handleAttemptClose}
                                        className="h-10 px-8 hover:bg-white hover:text-red-600 hover:border-red-200 transition-colors"
                                    >
                                        Cancelar
                                    </Button>
                                    <Button
                                        type="button"
                                        variant="outline"
                                        onClick={handlePrint}
                                        className="h-10 px-5 gap-2 hover:bg-white hover:text-blue-600 hover:border-blue-200 transition-colors"
                                        title="Imprimir esta OT (procesos + materias primas)"
                                    >
                                        <Printer className="w-4 h-4" />
                                        Imprimir
                                    </Button>
                                </div>
                                <div className="flex gap-3">
                                    {(activeTab === "procesos" || activeTab === "materias") && (
                                        <Button
                                            key="prev-button"
                                            type="button"
                                            variant="outline"
                                            onClick={handlePrevStep}
                                            className="h-10 px-6"
                                        >
                                            <ArrowLeft className="w-4 h-4 mr-2" />
                                            Anterior
                                        </Button>
                                    )}

                                    {activeTab === "procesos" ? (
                                        <Button
                                            key="submit-button"
                                            type="submit"
                                            disabled={submitting || loading}
                                            className="h-10 px-8 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg shadow-blue-500/30 transition-all hover:scale-[1.02]"
                                        >
                                            {submitting ? (
                                                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                            ) : (
                                                <CheckCircle2 className="mr-2 h-4 w-4" />
                                            )}
                                            Crear Orden
                                        </Button>
                                    ) : (
                                        <Button
                                            key="next-button"
                                            type="button"
                                            onClick={handleNextStep}
                                            className="h-10 px-8 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg shadow-blue-500/30 transition-all hover:scale-[1.02]"
                                        >
                                            Siguiente
                                            <ArrowRight className="ml-2 h-4 w-4" />
                                        </Button>
                                    )}
                                </div>
                            </div>
                        </DialogFooter>
                    </form>
                </DialogContent>
            </Dialog >
        </>
    );
}
