export { default as OrdenesCriticas } from "./OrdenesCriticas"
export { default as StatsCards } from "./StatsCards"
export { default as SectorOccupation } from "./SectorOccupation"
export { default as TimelineEntregas } from "./TimelineEntregas"
export { default as DistribucionPrioridades } from "./DistribucionPrioridades"
export { default as MostUsedProcesses } from "./MostUsedProcesses"
export { default as TopArticles } from "./TopArticles"
export { default as AverageTime } from "./AverageTime"

export { default as PriorityOrdersModal } from "./PriorityOrdersModal"
