from backend.domain.Proceso import Proceso
from backend.domain.RangoProceso import RangoProceso
from backend.domain.Rango import Rango
from backend.domain.OrdenTrabajoProceso import OrdenTrabajoProceso
from backend.domain.EstadoProceso import EstadoProceso
from backend.domain.Cliente import Cliente
from backend.domain.Pieza import Pieza
from backend.domain.OrdenTrabajo import OrdenTrabajo
from backend.domain.OrdenTrabajoPieza import OrdenTrabajoPieza
from backend.domain.OperarioProcesoSkill import OperarioProcesoSkill
from backend.domain.Articulo import Articulo
from backend.domain.Maquinaria import Maquinaria
from backend.domain.Operario import Operario
from backend.domain.OperarioRango import OperarioRango
from backend.domain.Planificacion import Planificacion
from backend.domain.Plano import Plano
from backend.domain.IncidenciaProceso import IncidenciaProceso
from backend.domain.Prioridad import Prioridad
from backend.domain.Sector import Sector
from backend.domain.Usuario import Usuario
from backend.domain.Notificacion import Notificacion

